SELECT * FROM users
SELECT * FROM user_hobby
SELECT * FROM customer
SELECT * FROM provider
SELECT * FROM appointment
SELECT * FROM appointment_rating
SELECT * FROM appointment_transaction
SELECT * FROM make_appointment
SELECT * FROM filter
SELECT * FROM activity_filter
SELECT * FROM search_by
SELECT * FROM chatroom
SELECT * FROM chat
SELECT * FROM message